language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
# command to run tests
script:
  - pytest --verbosity=2 --showlocals --strict --log-level=DEBUG
  - python setup.py build
branches:
  only:
    - develop
